games/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('www.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/urls.py
from django.urls import path
from django.views.generic import detail

from .views import *

urlpatterns = [
    # PATH
    path('', index, name='index'),
    path('game/<slug:slug>/', detail, name='detail'),
    path('company/<slug:slug>/', detail_company, name='detail_company'),
    path('all/games/', all_games, name='all_games'),
    path('all/company/', all_company, name='all_company'),

    # UTILS
    path('subscribe', subscribe, name='subscribe'),
]

www/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class ModelFavorite(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    game = models.ForeignKey('ModelGame', verbose_name="Игра", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.game}'

    class Meta:
        verbose_name = "Фаворит"
        verbose_name_plural = "Фавориты"
        unique_together = ('user', 'game')


class ModelGame(models.Model):
    name = models.CharField(verbose_name="Название", max_length=100)
    description = models.TextField(verbose_name="Описание", )
    company = models.ForeignKey('ModelCompany', verbose_name="Разработчик", on_delete=models.CASCADE)
    date_published = models.DateField(verbose_name="Дата выхода", )
    slug = models.SlugField(blank=True, unique=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ModelGame, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"


class ModelRating(models.Model):
    game = models.ForeignKey(ModelGame, verbose_name="Игра", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    value = models.IntegerField(verbose_name="Оценка", )

    def __str__(self):
        return f'{self.game} {self.value}'

    class Meta:
        verbose_name = "Оценка"
        verbose_name_plural = "Оценки"


class ModelCompany(models.Model):
    name = models.CharField(verbose_name="Название", max_length=100)
    country = models.CharField(verbose_name="Страна", max_length=100)
    description = models.TextField(verbose_name="Описание", )
    date_created = models.DateField(verbose_name="Дата основания", )
    slug = models.SlugField(blank=True, default='', editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ModelCompany, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Разработчик"
        verbose_name_plural = "Разработчики"


class ModelComment(models.Model):
    game = models.ForeignKey(ModelGame, verbose_name="Игра", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    comment = models.TextField(verbose_name="Комментарий", )
    date_of_creation = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.game} {self.user} {self.comment}'

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class ModelImageGame(models.Model):
    image = models.ImageField(verbose_name="Изображение", upload_to='images/')
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    game = models.ForeignKey(ModelGame, verbose_name="Игра", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.image}'

    class Meta:
        verbose_name = "Изображения для игры"
        verbose_name_plural = "Изображения для игр"


class ModelImageCompany(models.Model):
    image = models.ImageField(verbose_name="Изображение", upload_to='images/')
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    company = models.ForeignKey(ModelCompany, verbose_name="Разработчик", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.image}'

    class Meta:
        verbose_name = "Изображения для разработчиков"
        verbose_name_plural = "Изображения для разработчиков"


# теги к играм

www/views.py
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import *


def index(request):
    top_games = ModelGame.objects.annotate(
        favorite_count=Count('modelfavorite')).order_by('-favorite_count')[:4]

    favorite = ModelFavorite.objects.filter(user=request.user)
    favorite_game_ids = set(fav.game.id for fav in favorite)

    context = {
        'top_games': top_games,
        'favorite': favorite_game_ids,
    }

    return render(request, 'index.html', context=context)


def detail(request, slug):
    game = ModelGame.objects.get(slug=slug)

    return render(request, 'detail.html', context={'game': game})


def detail_company(request, slug):
    company = ModelCompany.objects.get(slug=slug)
    return render(request, 'detail-comp.html', context={'company': company})


def all_games(request):
    games = ModelGame.objects.all()
    favorite = ModelFavorite.objects.filter(user=request.user)
    favorite_game_ids = set(fav.game.id for fav in favorite)

    context = {
        'games': games,
        'favorite': favorite_game_ids
    }

    return render(request, 'all-games.html', context=context)


def all_company(request):
    company = ModelCompany.objects.all()

    context = {
        'company': company
    }

    return render(request, 'all-company.html', context=context)



################################################ UTILS ###############################################

def subscribe(request):
    game = ModelGame.objects.get(id=request.POST.get('game'))

    if ModelFavorite.objects.filter(user=request.user, game=game).exists():
        ModelFavorite.objects.filter(user=request.user, game=game).delete()
    else:
        ModelFavorite(user=request.user, game=game).save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

www/templates/all-company.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <H1>Все компании</H1>

    <div class="cards">
        {% for comp in company %}
            {% include 'include/company-card.html' with comp=comp %}
        {% endfor %}
    </div>

</div>
{% endblock %}

www/templates/all-games.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <H1>Все игры</H1>

        <div class="cards">
            {% for game in games %}
                {% include 'include/game-card.html' with game=game %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

www/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="RU">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <div class="wrap-logo">
        <a href="{% url 'index' %}" class="logo">CHTOTIM</a>
    </div>
    <nav>
        <a class="active" href="{% url 'index' %}">Главная</a>
        <a href="{% url 'all_games' %}">К играм</a>
        <a href="{% url 'all_company' %}">К компаниям</a>
        {% if user.is_authenticated %}
            <a href="{% url 'index' %}">Профиль ({{ user }})</a>
        {% else %}
            <a href="{% url 'index' %}">Войти</a>
        {% endif %}
    </nav>
</header>
{% block content %}
{% endblock %}
</body>
</html>

www/templates/detail-comp.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>{{ company.name }}</h1>
        <p>{{ company.description }}</p>
        <p>{{ company.country }}</p>
        <p>{{ company.date_created }}</p>
        {% for value in company.modelimagecompany_set.values %}
            <img class="img-detail" src="/media/{{ value.image }}" alt="{{ value.description }}">
        {% endfor %}
        <h1>Все игры {{ company.name }}</h1>
        {% for value in company.modelgame_set.values %}
            <p><a href="{% url 'detail' value.slug %}">{{ value.name }}</a></p>
        {% endfor %}
    </div>

{% endblock %}

www/templates/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>{{ game.name }}</h1>
        <p>{{ game.description }}</p>
        <a href="{% url 'detail_company' game.company.slug %}">{{ game.company }}</a>
        <p>{{ game.date_published }}</p>
        {% for value in game.modelimagegame_set.all %}
            <img class="img-detail" src="/media/{{ value.image }}" alt="{{ value.description }}">
        {% endfor %}
        <p>Фавориты: {{ game.modelfavorite_set.count }}</p>
        <h1>Комментарии</h1>

        {% if game.modelcomment_set.all %}
            {% for comment in game.modelcomment_set.all %}
                <p>{{ comment.user }}: {{ comment.comment }}</p>
            {% endfor %}
        {% else %}
            <p>Комментариев пока нет :(<br>будьте первым</p>
        {% endif %}

    </div>

{% endblock %}

www/templates/include/company-card.html
{% load static %}
<div class="card">
    <h3>{{ comp.name }}</h3>
    {% if comp.modelimagecompany_set.values.first.image %}
        <img src="/media/{{ comp.modelimagecompany_set.values.first.image }}" alt="">
    {% else %}
        <img src="{% static 'img/empty.png' %}" alt="">
    {% endif %}
    <a href="{% url 'detail_company' comp.slug %}">Перейти</a>
</div>

www/templates/include/game-card.html
{% load static %}
<div class="card">

    <h3>{{ game.name }}</h3>

    {% if game.modelimagegame_set.values.first.image %}
        <img src="/media/{{ game.modelimagegame_set.values.first.image }}" alt="">
    {% else %}
        <img src="{% static 'img/empty.png' %}" alt="">
    {% endif %}

    <small>Дата выхода: {{ game.date_published }}</small>
    <small>Разработчик: {{ game.company }}</small>
    <small>Подписались: {{ game.modelfavorite_set.count }}</small>

    <form method="post" action="{% url 'subscribe' %}">
        {% csrf_token %}

        <input type="hidden" name="game" value="{{ game.id }}"/>
        {% if game.id in favorite %}
            <button class="btn btn-red">Отписаться</button>
        {% else %}
            <button class="btn btn-green">Подписаться</button>
        {% endif %}

    </form>

    <a href="{% url 'detail' game.slug %}">Перейти</a>

</div>

www/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Лучшие игры</h1>

    <div class="cards">
        {% for game in top_games %}
            {% include 'include/game-card.html' with game=game %}
        {% endfor %}
    </div>

</div>
{% endblock %}